using System.Text;

namespace Tm2020Mcp.Maps;

/// <summary>
/// Learns a <see cref="BlockMotif"/> by looking at what sits around an anchor block across a
/// corpus, in the anchor's own frame of reference.
/// </summary>
public sealed class MotifLearner
{
    /// <param name="anchorName">Block the motif is measured around, e.g. PlatformTechLoopStart.</param>
    /// <param name="radius">How far to look horizontally.</param>
    /// <param name="heightBelow">Levels below the anchor to include; supports live down here.</param>
    /// <param name="heightAbove">Levels above the anchor to include.</param>
    /// <param name="threshold">
    /// Share of anchor sightings an offset must reach to join the motif. Too low and the
    /// motif absorbs whatever happened to be nearby in the maps sampled.
    /// </param>
    public BlockMotif Learn(
        IEnumerable<IReadOnlyList<MapBlock>> maps,
        string anchorName,
        int radius = 2,
        int heightBelow = 1,
        int heightAbove = 3,
        double threshold = 0.5,
        string canonicalDirection = "North",
        IReadOnlyList<string>? excludePrefixes = null)
    {
        // Two families in real maps are generated by the engine, not placed by an author,
        // and neither can be stamped back:
        //   DecoWall*   scenery - PlaceBlock answers "unknown block model"
        //   Structure*  the supports the game adds under elevated platforms - PlaceBlock
        //               refuses the coordinate, at ground level and elevated alike
        // Both were established by stamping them and reading the bridge's per-block errors.
        // Learning them into a motif yields a structure that can never be placed whole.
        excludePrefixes ??= ["DecoWall", "Structure"];
        var counts = new Dictionary<(int DX, int DY, int DZ, string Name, string Dir), int>();
        var anchors = 0;

        foreach (var blocks in maps)
        {
            var byCoord = new Dictionary<(int, int, int), MapBlock>();
            foreach (var block in blocks.Where(b => !b.IsFree))
                byCoord[(block.X, block.Y, block.Z)] = block;

            // Only anchors already facing the canonical direction, so offsets stay in one
            // frame. Rotation happens at stamp time, not here.
            foreach (var anchor in byCoord.Values.Where(b =>
                b.Name == anchorName
                && string.Equals(b.Direction, canonicalDirection, StringComparison.OrdinalIgnoreCase)))
            {
                anchors++;

                for (var dx = -radius; dx <= radius; dx++)
                for (var dy = -heightBelow; dy <= heightAbove; dy++)
                for (var dz = -radius; dz <= radius; dz++)
                {
                    if (!byCoord.TryGetValue((anchor.X + dx, anchor.Y + dy, anchor.Z + dz), out var block))
                        continue;

                    if (excludePrefixes.Any(prefix => block.Name.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)))
                        continue;

                    var key = (dx, dy, dz, block.Name, block.Direction);
                    counts[key] = counts.GetValueOrDefault(key) + 1;
                }
            }
        }

        if (anchors == 0)
            return new BlockMotif(anchorName, canonicalDirection, 0, []);

        // Support is counted per (offset, block), then the dominant direction is chosen.
        // Keying on direction directly would split a row that is structurally always there
        // but laid in mirrored orientations, and drop it below the threshold.
        var kept = counts
            .GroupBy(kv => (kv.Key.DX, kv.Key.DY, kv.Key.DZ, kv.Key.Name))
            .Select(group => new
            {
                group.Key,
                Total = group.Sum(kv => kv.Value),
                Direction = group.MaxBy(kv => kv.Value).Key.Dir
            })
            .Where(entry => entry.Total >= anchors * threshold)
            .Select(entry => new MotifBlock(
                entry.Key.DX,
                entry.Key.DY,
                entry.Key.DZ,
                entry.Key.Name,
                entry.Direction,
                Math.Round(Math.Min(1.0, (double)entry.Total / anchors), 3)))
            .OrderByDescending(b => b.Support)
            .ThenBy(b => b.DY)
            .ThenBy(b => b.DX)
            .ThenBy(b => b.DZ)
            .ToArray();

        return new BlockMotif(anchorName, canonicalDirection, anchors, kept);
    }

    public static string Format(BlockMotif motif)
    {
        if (motif.Samples == 0)
            return $"No grid instances of {motif.Anchor} facing {motif.CanonicalDirection} were found.";

        var report = new StringBuilder();
        report.AppendLine($"{motif.Anchor}: motif from {motif.Samples} instance(s) facing {motif.CanonicalDirection}, {motif.Blocks.Count} block(s).");
        report.AppendLine();

        foreach (var block in motif.Blocks)
            report.AppendLine($"  {block.Support,5:P0}  <{block.DX,3},{block.DY,3},{block.DZ,3}>  {block.Name,-28} {block.Direction}");

        return report.ToString().TrimEnd();
    }
}
